### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by pcarass** [alexed1/ItemsToApprove#4]
Hey @alexed1 
Just tried to install this and I'm receiving the follow error:
![Screen Shot 2020-03-22 at 13 34 03](https://user-images.githubusercontent.com/17454963/77250767-f9551c00-6c41-11ea-9fe6-78de493b3cd3.png)

I'm not really sure what the issue is, as I don't have any of those layouts or fields mentioned, in my org?
Anything you've seen before?
Cheers,
Paul

**Comment by alexed1** [comment]
Packaging error on my part. Those are pieces of metadata that shouldn't be in the final package. I've put a new link up (1.1.2).

**Comment by pcarass** [comment]
Awesome @alexed1 . Thanks for the quick turnaround!
